zachet = open("Names.txt", "w")
zachet.write("Усс\n")
zachet.write("Ярослав\n")
zachet.write("Хочу\n")
zachet.write("Залік\n")
zachet.write("492\n") 
zachet.close()
zachet = open("Names.txt", "r") 
print(zachet.read())
zachet.close()  