version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: ashotik
      POSTGRES_USER: ashotik
      POSTGRES_PASSWORD: ashotik
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: